### ISSUE TITLE
Provide a way to backport a PR to one or more branches

### ISSUE THREAD

**Issue by laeubi** [sqren/backport-github-action#99]
In a project we have two active branches:

- `master`
- `release-<previsous-version>`

I simply want that EVERY PR merged to master is automatically tried to be backported to the previous release.

It would therefore be great if one can simply specify the branch for the backport as an option instead of using a label at all.

**Comment by sqren** [comment]
Hi there,

Apologies for the late reply. You can already achieve this. Please create a file in your repo called `.backportrc.json`:
```
{
  "upstream": "{orgName}/{repoName}",
  "targetBranches": ["release-<previsous-version>"],
}
```

Please also update `.github/workflows/backport.yml`:
```
on:    
  pull_request_target:
    types: ["closed"]
    branches: ["master"]
jobs:
  backport:
    name: Backport PR
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true
      && (
        (github.event.action == 'labeled' && github.event.label.name == 'auto-backport')
        || (github.event.action == 'closed')
      )
    steps:
      - name: Backport Action
        uses: sqren/backport-github-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}    
```
